"""empty message

Revision ID: 024571c3c2f6
Revises: 27fcf828581d
Create Date: 2023-02-15 19:01:48.238760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024571c3c2f6'
down_revision = '27fcf828581d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
