"""empty message

Revision ID: 27fcf828581d
Revises: 41d723439e4a
Create Date: 2023-02-14 20:55:12.819929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27fcf828581d'
down_revision = '41d723439e4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
