"""empty message

Revision ID: 41d723439e4a
Revises: 0d73154826b5
Create Date: 2023-02-14 20:30:47.667550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d723439e4a'
down_revision = '0d73154826b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
