"""empty message

Revision ID: be4f16fd7308
Revises: 024571c3c2f6
Create Date: 2023-02-15 19:04:37.362537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be4f16fd7308'
down_revision = '024571c3c2f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
